common: &common
  adapter: postgresql
  username:
  password:
  host: localhost

development:
  <<: *common
  database: accounts_development

test:
  <<: *common
  database: accounts_test

production:
  <<: *common
  database: accounts_production
